{% set name = "Flask-SocketIO" %}
{% set version = "3.1.2" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "26fbb693f934ebb1c53a0944f11c761ed54897ca7a5b673ce98961072d0694c1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip

  run:
    - python
    - flask >=0.9
    - python-socketio >=2.1.0

test:
  imports:
    - flask_socketio
    - flask_socketio.cli
    - flask_socketio.namespace
    - flask_socketio.test_client

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Socket.IO integration for Flask applications'
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/

extra:
  recipe-maintainers:
    - pmlandwehr
