{% set name = "Flask-SocketIO" %}
{% set version = "2.9.1" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "62b86dc61515f9ef346cc36c371665457628a2ef3bae4323dca218f4514ee488" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  preserve_egg_dir: True
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.9
    - python-socketio >=1.5.0
    - python-engineio >=1.0.0

test:
  imports:
    - flask_socketio
    - flask_socketio.cli
    - flask_socketio.namespace
    - flask_socketio.test_client

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'Socket.IO integration for Flask applications'
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/

extra:
  recipe-maintainers:
    - pmlandwehr
