{% set name = "Flask-SocketIO" %}
{% set version = "5.3.1" %}
{% set bundle = "tar.gz" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: fd0ed0fc1341671d92d5f5b2f5503916deb7aa7e2940e6636cfa2c087c828bf9

build:
  skip: true  # [py<37]
  preserve_egg_dir: True
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel

  run:
    - python
    - flask >=0.9
    - python-socketio >=5.0.2

test:
  imports:
    - flask_socketio
    - flask_socketio.namespace
    - flask_socketio.test_client
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/miguelgrinberg/Flask-SocketIO/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  license_url: https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/LICENSE
  summary: 'Socket.IO integration for Flask applications'
  doc_url: https://flask-socketio.readthedocs.io/en/latest/
  dev_url: https://github.com/miguelgrinberg/Flask-SocketIO/
  doc_source_url: https://github.com/miguelgrinberg/Flask-SocketIO/blob/main/docs/index.rst
  description: |
    Flask-SocketIO gives Flask applications access to low 
    latency bi-directional communications between the clients
    and the server. The client-side application can use any
    of the SocketIO client libraries in Javascript, Python,
    C++, Java and Swift, or any other compatible client to
    establish a permanent connection to the server.

extra:
  recipe-maintainers:
    - pmlandwehr
    - synapticarbors
