travis:
  secure:
    BINSTAR_TOKEN: i4S6y1hS7VGNsmUWpcqkTai6LWcFgDJtexticOf3oU8uBV7x7DS4DNPO47zTXHxNSMqGmxwFuEK0eVSvaYLMTVYZ7pnghCpsamumfyv9V28btkME16xXHj4k5HCIxqWrDH+HsVtewlJ5pfiKkWIPhDfBotXorfZVPRMFQc09ZXTrxnmvPwMTL4u3gJx4a2N6wHsW35CB0Qp7iYTKAnnek2nLxhjPSL6AYn+D+T4hoGtKPVI3Jiw7ho2RSYzzyicNADjIFpD5CQVvw6EURnt4nhQUtKGFwVGE2scKBu4MO6YyAc47ZtkUnAcxbyi2TZnV8wMnOy1bJr0/8ltJE61Rh054Gi1RKhL0GcXuIAcu/PXwK6YfjuYCrg0xxU1/yg+QrOqkvimE0cX3g7jYcU7K4V17Axx5hIJACKButZOBOdd9OG2jm9G4GeSFgjzIIbh4srgq/npbocBsyHDNQl35/v/PiruH4d6UpRkRYG298Wqgnd5EX80XFFwjkEJDtcDDlIXsCsBFucd1/VoCaSyjuy1yxf/lPg2tl8Ibyuj0B3PghN00uoUyyT9PubWr8U5Io1SwOTXOI7R8V9u3xxnPDeiDYvO8niOivjSjEOG5C+W3Cq8dTn9Dp072thaMhNvL3f845vrbU69AIyssdn/Duh6324d4vxsH0oT7cA6BKk0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
